"""Constants for the Medusa integration."""

DOMAIN = "medusa"
CONF_FILE_PATH = "config_file"
CONF_PORT = "port"

DEFAULT_PORT = 1122  # Arbitrary compatible port

# Packet Types
PKT_TYPE_PING = 0x02
PKT_TYPE_DATA = 0x01
PKT_TYPE_ACTION_REQ = 0x10
PKT_TYPE_CONFIG = 0x05
PKT_TYPE_FINDER = 0xFF

PKT_TYPE_RELAY_CFG_REQ = 0xAA
PKT_TYPE_RELAY_CFG_RESP = 0xAB
PKT_TYPE_RELAY_ERROR = 0xAC
PKT_TYPE_RELAY_BOARD_DATA = 0xAD

# Actions
ACTION_MOTION = 0x01
ACTION_TEMP = 0x02
ACTION_LIGHT = 0x03
ACTION_DOOR = 0x04
ACTION_VOLT = 0x05
ACTION_VER = 0x06
ACTION_GAS = 0x07
ACTION_PRESSURE = 0x08
ACTION_ALTITUDE = 0x09
ACTION_BUZZER = 0x10
ACTION_FACTORY_RST = 0x11
ACTION_RELAY = 0x12
ACTION_LED = 0x13
ACTION_RESET = 0x14
ACTION_TEST = 0x16
ACTION_FLUSH_TX_FIFO = 0x17

# Signal dispatch constant
SIGNAL_MEDUSA_UPDATE = "medusa_update_{}_{}"  # string formatted with room, board_name
